### PR TITLE
Add support for vanilla.localhost/dir development

### PR DESCRIPTION
**Pull request by tburry**
Currently, our main dev setup is for https://dev.vanilla.localhost. It works, we’ve always developed like that, and why change? The answer: URL bugs.

## The Problem

The problem with developing against the root of a domain is that we are always introducing URL bugs by not calling the correct wrapper functions on URLs and static assets respectively. These bugs happen all the time no matter how senior the developer. They also waste a lot of time. The fact of the matter is we just won’t catch them ourselves so we need to improve our tools to catch them.

With this PR I am introducing the concept of always developing against a subdirectory. With this method, instead of developing like this:

https://dev.vanilla.localhost

You would develop like this:

https://vanilla.localhost/dev

So the idea is your site always looks like it is in a subdirectory. This will catch all bugs where URLs are not wrapped in the appropriate `url()` function. Client-side URLs will also fail in development if they haven’t been properly formatted.

## Other Benefits

This PR also allows you to specify *any* directory and not just `/dev`. When specifying another directory, you will in essence be accessing a different site. This allows developers to have as many local sites as they wish.

## Bugs Not Stopped

This config will not catch bugs of static assets that are wrapped in `url()` instead of `asset()`. Hopefully, some clever other dev comes up with a solution for that.

## TODO

- [x] nginx config file
- [x] bootstrap.before.php
- [ ] SSL cert
- [x] Docs

### CODE REVIEW

**Comment by tburry** [comment]
Can I get some help with the SSH key on this PR @DaazKu pretty please?

**Comment by DaazKu** [comment]
> SSH key

??

Do you mean self signed certificate?

**Comment by charrondev** [comment]
@DaazKu Yes. It seems to be a wildcard for just the subdomains, but does not actually work for the domain itself.

**Comment by DaazKu** [comment]
Yes so you have to create a self signed certificate for vanilla.locahost and then add it to the keychain in macsetup.sh

https://github.com/vanilla/vanilla-docker/blob/c419b935725a3346bf4b6ecaecaafdddf3014e5a/mac-setup.sh#L79-L83

**Comment by DaazKu** [comment]
You could also save yourself the trouble and create: `subdirectory.vanilla.localhost` and set it up to work with subdirectories :D

**Comment by charrondev** [comment]
I added the SSL certs.

**Comment by tburry** [comment]
@DaazKu 
> You could also save yourself the trouble and create: subdirectory.vanilla.localhost and set it up to work with subdirectories :D

vanilla.localhost is the new hotness.

**Pull request merged**
